name: Run UI Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size 2g
        ports:
          - 4444:4444

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execution permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run tests with remote Chrome
        run: ./gradlew clean test -DremoteUrl=http://localhost:4444/wd/hub

  
